apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  finalizers:
  - argoproj.io/finalizer
  name: argocd
spec:
  dex: {}
  rbac:
    defaultPolicy: 'role:admin'
  server:
    route:
      enabled: true
