apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${TEAM}
  namespace: ${CICD_NS}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'mydev'
      server: '*'
    - namespace: 'mystage
      server: '*'
  sourceRepos:
    - '*'
